// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Y3rVoZCgwj5dJhBOhrlA8VBVU86i_bI',
    appId: '1:693369441108:web:1b8864df8aa6f21e4656c1',
    messagingSenderId: '693369441108',
    projectId: 'firetest-123134',
    authDomain: 'firetest-123134.firebaseapp.com',
    storageBucket: 'firetest-123134.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfQIOfwCCsdclxIvRRR9C4xlYyST7d4N4',
    appId: '1:693369441108:android:25092a77b105ff964656c1',
    messagingSenderId: '693369441108',
    projectId: 'firetest-123134',
    storageBucket: 'firetest-123134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzNl2EmAE5BnxtvkzhlusS8t35i2NN3Q',
    appId: '1:693369441108:ios:813d089e2120f58c4656c1',
    messagingSenderId: '693369441108',
    projectId: 'firetest-123134',
    storageBucket: 'firetest-123134.appspot.com',
    iosClientId: '693369441108-u0pacdls86uo2nm6u61o1p2rtgnh0597.apps.googleusercontent.com',
    iosBundleId: 'com.example.internship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZzNl2EmAE5BnxtvkzhlusS8t35i2NN3Q',
    appId: '1:693369441108:ios:813d089e2120f58c4656c1',
    messagingSenderId: '693369441108',
    projectId: 'firetest-123134',
    storageBucket: 'firetest-123134.appspot.com',
    iosClientId: '693369441108-u0pacdls86uo2nm6u61o1p2rtgnh0597.apps.googleusercontent.com',
    iosBundleId: 'com.example.internship',
  );
}
